version: '3.8'

services:
  family-budget-postgre-sql:
    image: postgres:14.7-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - '5433:5432'
    volumes:
      - db-main:/var/lib/postgresql/data
    networks:
      - postgres

  family-budget-service:
    image: family-budget-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:80
    environment:
      ASPNETCORE_ENVIRONMENT: DockerCompose
    networks:
      - postgres
    depends_on:
      - family-budget-postgre-sql

networks:
  postgres:
    driver: bridge
volumes:
  db-main:
    driver: local